# Generated by Django 3.0.2 on 2020-07-12 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=700)),
                ('info', models.CharField(max_length=700)),
                ('pere_id', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_url', models.CharField(max_length=700)),
                ('info', models.CharField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lien',
            },
        ),
        migrations.CreateModel(
            name='Onglet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onglet',
            },
        ),
        migrations.CreateModel(
            name='Assoongletlien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lien')),
                ('onglet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Onglet')),
            ],
        ),
        migrations.CreateModel(
            name='Assoongletdossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dossier')),
                ('onglet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Onglet')),
            ],
        ),
        migrations.CreateModel(
            name='Assodossierlien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dossier')),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lien')),
            ],
        ),
    ]
